### ISSUE TITLE
Slim 4

### ISSUE THREAD

**Issue by radimvaculik** [o2ps/SlimNetteBridge#6]
Support new version of Slim. 

http://www.slimframework.com/docs/v4/start/upgrade.html

**Comment by jiripudil** [comment]
Hello, I am currently not actively using Slim nor this package, but I'll happily accept and review a pull request :)

**Comment by o5** [comment]
@radimvaculik A little bit late but you can check [slimapi/slimapi](https://bit.ly/2BydG1L). Latest Slim + Nette DI and more (a lot of features will be added soon). Important thing: I'm author and it's inspired by this project!

**Comment by radimvaculik** [comment]
@o5 Thanks!
